spring:
  application:
    name: config-client
  config:
    # Подключение к Config Server при старте приложения
    import: "optional:configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
